spring.application.name=backend

server.port=4000

spring.datasource.url=jdbc:mysql://localhost:3306/gasStationPrices?allowPublicKeyRetrival=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=roberto_24
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

jwt.secret=TuClaveSuperLargaDeAlMenos64CaracteresParaHS5120123456789012345678901234567890123456789012345678901234567890
jwt.expiration=86400000